#!/bin/bash

# This checks /proc/cmdline for the LAST 'flash=' statement, and uses its value
# as a /dev entry to mount it read-only into /flash/

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
FLASHDIR=/flash
FAIL_IN_ERROR=

mount_flash_ro() {
  local flash

  unset FLASH_MBR FLASH_HW FLASH_SW

  if [ -s /var/state/flash-layout.rc ]; then
    . /var/state/flash-layout.rc
  fi

  if [ -z "$FLASH_SW" ]; then
    if [ -x /sbin/mk-flash-layout ]; then
      /sbin/mk-flash-layout -k && return 0
      if [ -s /var/state/flash-layout.rc ]; then
        . /var/state/flash-layout.rc
      fi
    fi
  fi

  if [ -z "$FLASH_SW" ]; then
    flash="$(cat /proc/cmdline)"
    if [ -n "${flash##*flash=*}" ]; then
      echo "No flash block device found on this system."
      return 1
    fi
    flash=${flash##*flash=}
    flash=${flash%% *}
    [ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
  else
    flash=$FLASH_SW
  fi

  echo "Mounting ${flash} on $FLASHDIR..."
  cd /
  umount -n -d $FLASHDIR >/dev/null 2>&1
  if ! mount -n -r $flash $FLASHDIR >/dev/null 2>&1; then
    echo "Error: mount failed."
    return 1
  fi

  [ -d $FLASHDIR/cfg/. ] && return 0

  # $FLASHDIR/cfg doesn't exist. Either it's a jffs2 and it was not formated,
  # or it's another FS mounted for the first time and we'd rather create it
  # now, because leaving this device mounted makes it unusable for anything.
  if [ -z "${flash##*jffs2*}" ] || \
    ! mount -wo remount $FLASHDIR >/dev/null 2>&1 || \
    ! mkdir -m 0755 -p $FLASHDIR/cfg >/dev/null 2>&1 || \
    ! mount -ro remount $FLASHDIR >/dev/null 2>&1; then
    if [ -n "$FAIL_ON_ERROR" ]; then
      umount -n -d $FLASHDIR >/dev/null 2>&1
      echo "Error: flash partition not formated yet."
      return 1
    else
      echo "Warning: flash partition not formated yet."
      return 0
    fi
  fi
  return 0
}

if [ "$1" = "-e" ]; then
  FAIL_ON_ERROR=1
fi

mount_flash_ro
